apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
  name: prometheus-k8s
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9090
    targetPort: 9090
    nodePort: 30834
  type: NodePort
  selector:
    app: prometheus
    prometheus: k8s
